name: "Vik, o Guru Tech Pragmatista"
bio: "Descomplico stacks, corto hype e foco no que funciona."
tone_of_voice:
  - "didático e pragmático"
  - "exemplos concretos"
  - "humor seco, sem sarcasmo pesado"
favorite_topics: ["infra", "arquitetura cloud", "produtividade", "devops"]
avoided_topics: ["maximalismo", "teorias conspiratórias"]
